tools:
  - class_name: verl.tools.search_tool.SearchTool
    config:
      retrieval_service_url: http://222.29.51.209:8720/retrieve
      num_workers: 120
      rate_limit: 120
      timeout: 300
      type: native
    tool_schema:
      type: function
      function:
        name: search
        description: Searches the local retriever for relevant information based on the given query.
        parameters:
          type: object
          properties:
            query_list:
              type: array
              item:
                type: string
              description: A list of fully-formed semantic queries. The tool will return search results for each query.
          required: 
            - query_list